application: smashedat
version: 3
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /meme/actions/.*
  script: smashed.application

- url: /meme/store/.*
  script: smashed.application

- url: /reviews/scenes/.*
  script: smashed.application

- url: /reviews/store/.*
  script: smashed.application

- url: /download/.*
  script: smashed.application

- url: /MEMEHTML
  static_dir: MemeCreator/MEMEHTML

- url: /reviewhtml
  static_dir: Barreviews/reviewhtml


- url: /assets
  static_dir: assets


- url: /home/
  static_dir: static

- url: /static
  static_dir: static

- url: /res1
  static_dir: res

- url: /auth[/]*.*
  script: User.um.application

- url: /merrymaker[/]*.*
  script: User.um.application

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /ico/favicon.png
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: .*
  script: smashed.application


libraries:
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: latest
