application: smashedat
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /MEMEHTML
  static_dir: MEMEHTML
  
- url: /reviewhtml
  static_dir: Reviews/reviewhtml
  
- url: /meme
  static_dir: views
  
- url: /reviews
  static_dir: Reviews/views
  
- url: /actions/.*
  script: store.application
  
- url: /download/.*
  script: store.application
  
libraries:
- name: PIL
  version: latest
